### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by SrX** [DNS-OARC/dnsmeter#21]
Hello!

I was wondering if it’s possible to add support for IPv6 to the dnsmeter?

My bests,

**Comment by jelu** [comment]
Adding IPv6 support is fully possible but quite an undertaking since `dnsmeter` uses spoofing to send the traffic and capturing to read the return traffic.

You are more then welcome to try and implement support for IPv6 and send a pull request.

Or if you wish to fund this development we can start working on a Statement of Work, see [Funding Development](https://www.dns-oarc.net/oarc/software) for more information.

**Comment by pspacek** [comment]
@jelu What about leaving this open, so it is easier to find? Pretty please ...

**Comment by jelu** [comment]
@pspacek pretties please lets not :) don't want to leave issues open that are most likely never getting done. + this project is in maintenance only.

**Comment by pspacek** [comment]
Well okay, so can you add a warning to README? It's PITA to waste time on compiling something to find out it cannot do IPv6.

**Comment by jelu** [comment]
@pspacek sure, but why compile when there are packages? :P
